In [1]:
# 1. Setup import path
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
# 2. Import modules
from src.kotoba_preprocessing import preprocess_dataset
from src.kotoba_features import add_features

In [8]:
# 3. Define file path
file_path = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "yahoo_questions.csv"
)

In [17]:
# 4. Run preprocessing pipeline
long_df, token_df = preprocess_dataset(file_path)

In [18]:
# 5. Feature engineering
long_df = add_features(long_df)

In [19]:
# 6. Quick inspection
long_df.head()

,id,text,tokens,token_count,label,sentences,sentence_token_lengths,connectives,connective_count,connective_density,sentence_endings,normalized_endings,ending_diversity,ending_entropy,pronouns,pronoun_count,pronoun_density,kanji_ratio,kana_ratio,kanji_to_kana
0,1,アイドルのライブでしたらそういう人もいるかもしれませんが、バンド系のライブでしょうか？\r\...,"[アイドル, の, ライブ, でし, たら, そう, いう, 人, も, いる, か, も,...",33,human,"[アイドルのライブでしたらそういう人もいるかもしれませんが、バンド系のライブでしょうか, め...","[23, 7]",[],0,0.000000,"[系のライブでしょうか, 目立ちすると思います]","[系のライブでしょうか, 目立ちすると思います]",1.0,1.000000,[人],1,0.030303,0.095238,0.825397,0.113208
1,2,基本的な塗料というのは原液の様に濃く作られているからです。\r\n\r\n子供の頃に学校で使...,"[基本的, な, 塗料, と, いう, の, は, 原液, の, 様, に, 濃く, 作ら,...",69,human,"[基本的な塗料というのは原液の様に濃く作られているからです, 子供の頃に学校で使った絵の具や...","[18, 48]",[],0,0.000000,"[作られているからです, だりしているわけです]","[作られているからです, だりしているわけです]",1.0,1.000000,[],0,0.000000,0.267857,0.625000,0.422535
2,3,＞みなさんは放置子に付き纏われたりした際、付き合ってあげますか？\r\n\r\n以前の私なら...,"[＞, みな, さん, は, 放置, 子, に, 付き纏わ, れ, たり, し, た, 際,...",79,human,"[＞みなさんは放置子に付き纏われたりした際、付き合ってあげますか, 以前の私なら付き合ってあ...","[19, 11, 34, 7]",[],0,0.000000,"[付き合ってあげますか, ってあげたと思います, 付き合ってあげません, に放置子から離れます]","[付き合ってあげますか, ってあげたと思います, 付き合ってあげません, に放置子から離れます]",1.0,2.000000,"[私, 私]",2,0.025316,0.238095,0.626984,0.375000
3,4,EUに加盟することとEURを使うことは同じではありませんが\r\nEU再加盟の機運は高くなっ...,"[EU, に, 加盟, する, こと, と, EUR, を, 使う, こと, は, 同じ, ...",121,human,[EUに加盟することとEURを使うことは同じではありませんが\r\nEU再加盟の機運は高くな...,[120],[],0,0.000000,[室紋章などでしょうね],[室紋章などでしょうね],1.0,-0.000000,[],0,0.000000,0.228155,0.601942,0.376000
4,5,南アフリカ共和国およびその周辺の国々。\r\n\r\nアフリカの大自然の中で人間に保護されな...,"[南アフリカ共和国, および, その, 周辺, の, 国々, 。, \r\n\r\n, アフ...",51,human,"[南アフリカ共和国およびその周辺の国々, アフリカの大自然の中で人間に保護されながら生息して...","[6, 32, 9]",[また],1,0.019608,"[およびその周辺の国々, ゾウ・カバ)を観たい, 瀑布を見学したいから]","[およびその周辺の国々, ゾウ・カバ)を観たい, 瀑布を見学したいから]",1.0,1.584963,[],0,0.000000,0.227723,0.663366,0.338235

In [20]:
# 7. Sanity checks
long_df.groupby("label")["token_count"].describe()

       count    mean         std   min    25%    50%     75%    max
label
ai      50.0  229.36  103.281221  31.0  141.0  247.0  290.00  425.0
human   50.0  117.68   67.208916  33.0   65.0   95.5  160.75  320.0